# Between RIOT releases, this file points all projects in the tree to git
# versions (still respecting Cargo.lock).
#
# Authors of out-of-tree applications can use the same lines in their
# Cargo.toml, copy this file over, or just use the released versions.

[patch.crates-io]
riot-sys = { git = "https://github.com/RIOT-OS/rust-riot-sys", rev = "4e99981b66305566740af7009482fdc0f6bd1192" }
riot-wrappers = { git = "https://github.com/RIOT-OS/rust-riot-wrappers", rev = "006e35d904417abbf97044ce1a1fc55bbb47a4a0" }
